# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build fetch`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t fetch`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system fetch && \
          adduser --system -G fetch fetch

COPY dist/fetch fetch/
RUN chown -R fetch:fetch .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix fetch --omit=dev -f install

CMD [ "node", "fetch" ]
